"use client";

import { useMemo, useState } from "react";
import { Info, Phone, Mail, FileText } from "lucide-react";
import { DateRangeSelector } from "@/components/dashboard/date-range-selector";
import { DashboardSkeleton } from "@/components/dashboard/loading-state";
import { ErrorBanner } from "@/components/dashboard/error-banner";
import { EmptyState } from "@/components/dashboard/empty-state";
import { MetricCard } from "@/components/dashboard/metric-card";
import { TrendChart, BarMetricChart, DonutChartCard } from "@/components/dashboard/chart-card";
import { RankedList } from "@/components/dashboard/ranked-list";
import { InsightList } from "@/components/dashboard/insight-list";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useAdsData } from "@/hooks/use-ads-data";
import { formatCurrency, formatNumber, formatPercent, percentChange } from "@/lib/utils";
import type { DateRangeValue } from "@/types/dashboard";

const trackedActions = [
  { icon: Phone, label: "Phone Calls", helper: "Click-to-call taps from paid visitors" },
  { icon: FileText, label: "Form Submissions", helper: "Contact and quote forms completed" },
  { icon: Mail, label: "Email Clicks", helper: "Email link taps from paid visitors" },
];

export default function GoogleAdsPage() {
  const [range, setRange] = useState<DateRangeValue>("30d");
  const { data, isLoading, error } = useAdsData(range);
  const ads = data?.ads;

  const insights = useMemo(() => {
    if (!ads) return [];

    const leadChange = percentChange(ads.paidLeads, ads.previous.paidLeads);
    const topCampaign = ads.campaigns[0]?.name ?? "your active campaigns";

    const list = [
      `${ads.paidLeads.toLocaleString()} leads came from Google Ads — phone calls, form submissions, and email clicks combined.`,
      `Paid lead actions are ${Math.abs(leadChange).toFixed(1)}% ${leadChange >= 0 ? "higher" : "lower"} than the previous period.`,
    ];

    if (ads.hasCostData) {
      list.push(
        `You spent ${formatCurrency(ads.adCost)} on Google Ads, which works out to ${formatCurrency(ads.costPerLead)} per lead.`,
        `${topCampaign} is currently your most active paid campaign by website visits.`,
      );
    } else {
      list.push(
        `${ads.paidSessions.toLocaleString()} website visits came from paid search in this period.`,
        `${topCampaign} is currently your most active paid campaign by website visits.`,
      );
    }

    return list.slice(0, 4);
  }, [ads]);

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <p className="text-sm font-semibold uppercase tracking-[0.14em] text-primary">Google Ads</p>
          <h1 className="mt-2 text-3xl font-semibold tracking-normal text-slate-950">Paid advertising performance</h1>
          <p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">
            Spend, clicks, and leads generated by your Google Ads campaigns.
          </p>
        </div>
        <DateRangeSelector value={range} onChange={setRange} />
      </div>

      {isLoading && <DashboardSkeleton />}

      {!isLoading && (
        <>
          <ErrorBanner errors={error ? [error] : []} />

          {!ads ? (
            <EmptyState
              title="Google Ads data unavailable"
              message="Confirm GA4_PROPERTY_ID is set and the service account has access to the GA4 property that receives your Google Ads traffic."
            />
          ) : (
            <>
              {!ads.hasCostData && (
                <div className="flex items-start gap-3 rounded-lg border border-amber-200 bg-amber-50 p-4">
                  <Info className="mt-0.5 h-5 w-5 shrink-0 text-amber-600" />
                  <div>
                    <p className="text-sm font-semibold text-amber-900">Ad spend figures are not showing yet</p>
                    <p className="mt-1 text-sm leading-6 text-amber-800">
                      Lead and visit numbers below are live. To also show cost, clicks, and cost-per-lead, link your
                      Google Ads account to Google Analytics (GA4 Admin → Product Links → Google Ads Links). Once linked,
                      spend data appears here automatically.
                    </p>
                  </div>
                </div>
              )}

              <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
                <MetricCard
                  label="Paid Leads"
                  value={ads.paidLeads}
                  helper="Calls, forms, and email clicks from Google Ads."
                  change={percentChange(ads.paidLeads, ads.previous.paidLeads)}
                />
                <MetricCard
                  label="Ad Spend"
                  value={ads.hasCostData ? formatCurrency(ads.adCost) : "—"}
                  helper={ads.hasCostData ? "Total Google Ads cost this period." : "Available once Google Ads is linked to GA4."}
                  change={ads.hasCostData ? percentChange(ads.adCost, ads.previous.adCost) : undefined}
                />
                <MetricCard
                  label="Cost Per Lead"
                  value={ads.hasCostData ? formatCurrency(ads.costPerLead) : "—"}
                  helper={ads.hasCostData ? "Average ad cost for each lead generated." : "Available once Google Ads is linked to GA4."}
                  change={
                    ads.hasCostData && ads.previous.costPerLead
                      ? ((ads.previous.costPerLead - ads.costPerLead) / ads.previous.costPerLead) * 100
                      : undefined
                  }
                />
                <MetricCard
                  label={ads.hasCostData ? "Paid Clicks" : "Paid Visits"}
                  value={ads.hasCostData ? ads.adClicks : ads.paidSessions}
                  helper={ads.hasCostData ? "Clicks on your Google Ads." : "Website visits from paid search."}
                  change={
                    ads.hasCostData
                      ? percentChange(ads.adClicks, ads.previous.adClicks)
                      : percentChange(ads.paidSessions, ads.previous.paidSessions)
                  }
                />
              </div>

              <InsightList insights={insights} />

              <TrendChart
                title="Google Ads Trend"
                description={
                  ads.hasCostData
                    ? "Daily ad spend and leads generated from Google Ads."
                    : "Daily leads generated from paid search visits."
                }
                data={ads.trends}
                lines={
                  ads.hasCostData
                    ? [
                        { key: "adCost", name: "Ad Spend", color: "#B7791F" },
                        { key: "paidLeads", name: "Leads", color: "#16865A" },
                      ]
                    : [{ key: "paidLeads", name: "Leads", color: "#16865A" }]
                }
              />

              <div className="grid gap-4 xl:grid-cols-2">
                <BarMetricChart
                  title="Top Campaigns"
                  description="Paid campaigns ranked by website visits."
                  data={ads.campaigns}
                  valueLabel="Visits"
                />
                <DonutChartCard
                  title="Paid Lead Breakdown"
                  description="How leads from Google Ads reached you."
                  data={ads.conversions.map((item) => ({ name: item.label, value: item.count }))}
                />
              </div>

              <div className="grid gap-4 xl:grid-cols-[1fr_0.9fr]">
                <RankedList
                  title="Paid Performance Summary"
                  description={`Conversion rate: ${formatPercent(ads.conversionRate)}.${
                    ads.hasCostData
                      ? ` Click-through rate: ${formatPercent(ads.adCtr)}. Avg. cost per click: ${formatCurrency(ads.costPerClick)}.`
                      : ""
                  }`}
                  data={[
                    { name: "Paid Visits", value: ads.paidSessions, helper: "Website visits from Google Ads" },
                    ...(ads.hasCostData
                      ? [
                          { name: "Ad Clicks", value: ads.adClicks, helper: "Clicks on your ads" },
                          { name: "Ad Impressions", value: ads.adImpressions, helper: "Times your ads were shown" },
                        ]
                      : []),
                    { name: "Paid Leads", value: ads.paidLeads, helper: "Calls, forms, and email clicks" },
                  ]}
                  valueLabel="Total"
                />

                <Card>
                  <CardHeader>
                    <CardTitle>What we track</CardTitle>
                    <CardDescription>The lead actions counted from your Google Ads campaigns.</CardDescription>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-3">
                      {trackedActions.map((action) => {
                        const Icon = action.icon;
                        return (
                          <div key={action.label} className="flex items-start gap-3 rounded-md border border-border p-3">
                            <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-md bg-[#F7FBFF] text-primary">
                              <Icon className="h-4 w-4" />
                            </span>
                            <div>
                              <p className="text-sm font-semibold text-slate-950">{action.label}</p>
                              <p className="mt-0.5 text-xs leading-5 text-slate-500">{action.helper}</p>
                            </div>
                          </div>
                        );
                      })}
                      <p className="px-1 pt-1 text-xs leading-5 text-slate-400">
                        Lead totals reflect {formatNumber(ads.paidSessions)} paid visits in the selected date range.
                      </p>
                    </div>
                  </CardContent>
                </Card>
              </div>
            </>
          )}
        </>
      )}
    </div>
  );
}
